export const english: Record<string, string> = {
  "Linea chiara": "Clear line",
  "contorni neri uniformi, colori piatti, sfondi precisi": "uniform black outlines, flat colours, detailed backgrounds",
  "Noir a china": "Ink noir",
  "bianco e nero, neri pieni, contrasti forti": "black and white, solid blacks, strong contrast",
  "Manga in bianco e nero": "Black-and-white manga",
  "pennino, retini, espressioni marcate": "pen lines, screentones, expressive faces",
  "Graphic novel ad acquerello": "Watercolour graphic novel",
  "china e acquerello, palette terrosa, carta": "ink and watercolour, earthy palette, paper texture",
  "Satira grottesca": "Grotesque satire",
  "caricatura, tratteggio nervoso, colori acidi e spenti": "caricature, scratchy hatching, muted acidic colours",
  "Webtoon a colori": "Colour webtoon",
  "linee pulite digitali, ombre morbide, colori vivi": "clean digital lines, soft shadows, vivid colours",
  "corporatura": "build",
  "carnagione": "skin tone",
  "arte": "artwork",
  "copione": "script",
  "pagina": "page",
  "personaggio": "character",
  "luogo": "location",
  "luogo e ora": "location and time",
  "scheda di": "sheet for",
  "tutto il capitolo": "entire chapter",
  "+ in vignetta": "+ add to panel",
  "(cap.": "(ch.",
  "documento": "document",
  "istruzioni": "instructions",
  "parametri": "parameters",
  "mancante": "missing",
  "schizzo": "sketch",
  "inchiostrato": "inked",
  "colorato": "coloured",
  "finito": "finished",
  "spoglio": "breakdown",
  "aggiornata": "up to date",
  "nessuna.": "none.",
  "nessuna": "none",
  "nessuno": "none",
  "corrente": "current",
  "errore": "error",
  "errori": "errors",
  "avviso": "warning",
  "avvisi": "warnings",
  "nota": "note",
  "note": "notes",
  "campo": "field",
  "continuità": "continuity",
  "sostituzione": "replacement",
  "protagonista": "lead",
  "secondario": "supporting",
  "sfondo": "background",
  "solo testa": "head only",
  "solo mani": "hands only",
  "supina": "worm's-eye view",
  "olandese": "Dutch angle",
  "soggettiva": "point of view",
  "dettaglio": "detail",
  "fronte": "front",
  "tre quarti": "three-quarter",
  "(copione vuoto)": "(empty script)",
  " (non nella scheda)": " (not in the sheet)",
  " (solo in {0})": " (only in {0})",
  " (uguale in tutti i formati)": " (same in every format)",
  " ({0} corte)": " ({0} short)",
  " ({0} corte, per non tagliare l'arte)": " ({0} short, to avoid cropping artwork)",
  " La tua vince su quella generata.": " Your artwork takes priority over the generated image.",
  " Resta in questa scheda finché non salvi il progetto in una cartella.": " Kept in this tab until you save the project to a folder.",
  " Una correzione che vale per tutta la serie si segna in Revisioni, con «vale per la serie…»: da lì arriva qui.": " Mark a series-wide correction in Revisions with “apply to series…”: it will appear here.",
  " e il riassunto del capitolo precedente": " and the previous chapter's summary",
  " in {0}": " in {0}",
  ": clic per toglierla": ": click to remove",
  "Ctrl+Z lo riporta.": "Ctrl+Z restores it.",
  "Il progetto non ha un formato a striscia": "This project has no strip format",
  "Ingrandisce / rimpicciolisce": "Zoom in / out",
  "Istruzioni per modelli esterni": "Instructions for external models",
  "La riapertura automatica dell'ultimo progetto non è riuscita: aprilo da «Apri progetto…».": "Could not reopen the last project automatically: use “Open project…”.",
  "Il progetto è stato aperto da {0}: salvataggio automatico sospeso per non sovrascriverlo.": "The project was opened by {0}: autosave paused to avoid overwriting it.",
  "La cartella \"{0}\" contiene già un progetto. Sostituirlo con quello aperto qui?\n\n": "The folder “{0}” already contains a project. Replace it with the current one?\n\n",
  "Per lavorare su quello esistente, usa invece «Apri».": "To work on the existing project, use “Open” instead.",
  "Questo progetto risulta aperto da {0} (ultimo segnale alle {1}).\n\n": "This project is open by {0} (last seen at {1}).\n\n",
  "Se lo apri anche qui, le due finestre si sovrascriveranno a vicenda. Aprire lo stesso?": "Opening it here too may cause the two windows to overwrite each other's changes. Open anyway?",
  "Permesso negato per «{0}»: aprilo da «Apri progetto…».": "Access denied to “{0}”: use “Open project…”.",
  "Riferimento non trovato: {0}. Toglilo {1}, o rimetti il file.": "Reference not found: {0}. Remove it {1}, or restore the file.",
  "Risponde, con {0} caricato.": "Responding, with {0} loaded.",
  "Risponde, ma ha caricato «{0}»: lo spec registra FLUX.2 [klein] 4B, e i render direbbero il falso. Avvialo con klein 4B.": "Responding, but “{0}” is loaded: the specification records FLUX.2 [klein] 4B, so renders would be mislabelled. Start it with klein 4B.",
  "Richiesta annullata": "Request cancelled",
  "Scelta annullata": "Selection cancelled",
  "Canvas 2D non disponibile": "Canvas 2D unavailable",
  "Conversione in {0} fallita ({1}×{2} px)": "Conversion to {0} failed ({1}×{2} px)",
  "Dati da scrivere di un tipo non gestito": "Unsupported data type for writing",
  "Font non trovato ({0}): {1}": "Font not found ({0}): {1}",
  "L'SVG non è stato caricato come immagine": "The SVG could not be loaded as an image",
  "Nome di file vuoto: \"{0}\"": "Empty filename: “{0}”",
  "Percorso vuoto: \"{0}\"": "Empty path: “{0}”",
  "{0} non trovato": "{0} not found",
  "{0} è un file": "{0} is a file",
  "{0} è una cartella": "{0} is a folder",
  "desktopFetch fuori dall'app desktop": "desktopFetch outside the desktop app",
  "desktopFetch: corpo della richiesta di un tipo non gestito": "desktopFetch: unsupported request body type",
  "Senza titolo": "Untitled",
  "Studio piccolo con il soffitto basso. Scrivania di legno chiaro sotto una finestra con il vetro incrinato, a sinistra; sedia ergonomica rossa; libreria bianca sul fondo. Pavimento in graniglia grigia. Di giorno luce fredda dalla finestra, di sera solo il monitor.": "Small study with a low ceiling. Light wood desk under a cracked window on the left; red ergonomic chair; white bookcase at the back. Grey terrazzo floor. Cool window light by day, monitor light only at night.",
  "grigio freddo, legno chiaro, rosso della sedia": "cool grey, light wood, red chair",
  "tecnica del faro, testarda": "stubborn lighthouse technician",
  "Lingua dell'interfaccia": "Interface language",
  "Copione": "Script",
  "Pagine": "Pages",
  "Riferimenti": "References",
  "Revisioni": "Revisions",
  "Progetto": "Project",
  "Salva": "Save",
  "Salva…": "Save…",
  "Annulla": "Undo",
  "Ripeti": "Redo",
  "Chiudi": "Close",
  "Non salvato: il progetto vive solo in questa scheda.": "Not saved: this project exists only in this browser tab.",
  "Modifiche in attesa di salvataggio…": "Changes waiting to be saved…",
  "Salvo…": "Saving…",
  "Salvato in «{0}» alle {1}.": "Saved to “{0}” at {1}.",
  "Salvataggio non riuscito: {0}": "Could not save: {0}",
  "non salvato": "not saved",
  "da salvare…": "unsaved changes…",
  "salvo…": "saving…",
  "salvato {0}": "saved {0}",
  "salvataggio fallito": "save failed",
  "sola lettura": "read only",
  "Nome del nuovo progetto?": "New project name?",
  "Nome del nuovo progetto?\n\nAttenzione: il progetto aperto non è salvato in una cartella e andrà perso.": "New project name?\n\nWarning: the current project has not been saved to a folder and will be lost.",
  "Nome del progetto": "Project name",
  "Clicca per rinominare il progetto": "Click to rename the project",
  "Capitolo aperto": "Current chapter",
  "senza titolo": "untitled",
  "Area di lavoro": "Workspace",
  "Capitoli, testo e spoglio": "Chapters, script and breakdown",
  "Pagine, vignette, balloon, arte": "Pages, panels, balloons and artwork",
  "Stile, personaggi e luoghi dell'opera: ciò che tiene uguali le vignette": "Style, characters and locations: visual consistency across panels",
  "Correzioni dello sceneggiatore, trova e sostituisci": "Writer corrections, find and replace",
  "Il capitolo nei formati del progetto": "The chapter in the project's formats",
  "Annulla «{0}»": "Undo “{0}”",
  "Ripeti ({0}Shift+Z)": "Redo ({0}Shift+Z)",
  "Salva in «{0}»": "Save to “{0}”",
  "Salva il progetto in una cartella": "Save the project to a folder",
  "Il browser chiede di nuovo il permesso per la cartella": "The browser needs permission to access the folder again",
  "Riapri «": "Reopen “",
  "Scorciatoie da tastiera (?)": "Keyboard shortcuts (?)",
  "Scorciatoie da tastiera": "Keyboard shortcuts",
  "cartella: {0}": "folder: {0}",
  "nessuna cartella": "no folder",
  "Nuovo progetto…": "New project…",
  "Apri progetto…": "Open project…",
  "Salva in un'altra cartella…": "Save to another folder…",
  "Salva in una cartella…": "Save to a folder…",
  "Questo browser non apre cartelle: per salvare il progetto serve Chrome o Edge.": "This browser cannot open folders: use Chrome or Edge to save the project.",
  "Configurazione…": "Settings…",
  "Modelli locali…": "Local models…",
  "Ripristinato il lavoro di questa scheda (": "Restored this tab's work (",
  "ricomincia da capo": "start over",
  "Il testo del capitolo": "The script for chapter",
  ". Lo spoglio lo divide in scene, pagine e vignette": ". Breakdown divides it into scenes, pages and panels",
  "; rifarlo sostituisce le pagine del capitolo (Ctrl+Z le riporta)": "; running it again replaces the chapter's pages (Ctrl+Z restores them)",
  "capitoli dell'opera": "project chapters",
  "cosa sa lo spoglio": "breakdown context",
  "Capitolo": "Chapter",
  "— vuoto": "— empty",
  "Questo capitolo non ha ancora pagine: nascono dallo spoglio del copione.": "This chapter has no pages yet: run the script breakdown to create them.",
  "Vai al copione": "Go to script",
  "locale": "local",
  "euristico": "heuristic",
  "Spoglio {0} · {1}/{2}": "Breakdown {0} · {1}/{2}",
  "Il copione o le pagine sono cambiati durante lo spoglio. I risultati non sono stati applicati: rilancia il lavoro.": "The script or pages changed during breakdown. Results were not applied: run it again.",
  "Lo spoglio non ha prodotto pagine.": "Breakdown did not produce any pages.",
  "Schede personaggio riempite dallo spoglio (dove il testo tace è una proposta), da rivedere: {0}": "Character sheets filled in by breakdown (details not in the script are suggestions), please review: {0}",
  "Luoghi descritti dallo spoglio, da rivedere in Riferimenti → Luoghi: {0}": "Locations described by breakdown, review in References → Locations: {0}",
  "Ovunque": "Everywhere",
  "Questa legenda": "This shortcut list",
  "Aree: Copione, Pagine, Riferimenti, Revisioni, Export": "Areas: Script, Pages, References, Revisions, Export",
  "Capitolo precedente / successivo": "Previous / next chapter",
  "Shift + Pag↑ / Pag↓": "Shift + PageUp / PageDown",
  "Esce dal campo in cui scrivi: da lì i tasti sono comandi": "Leave the text field to use keyboard commands",
  "In un elenco": "In a list",
  "Voce vicina: capitolo, pagina, vignetta, stile, personaggio, luogo": "Adjacent item: chapter, page, panel, style, character, location",
  "Voce precedente / successiva": "Previous / next item",
  "Sposta il capitolo o la pagina": "Move the chapter or page",
  "Elimina il capitolo o la pagina": "Delete the chapter or page",
  "Alt + frecce": "Alt + arrows",
  "Shift + frecce": "Shift + arrows",
  "Mentre scrivi in un campo le lettere sono testo:": "While editing a field, letters are text:",
  "esce dal campo, e da lì i tasti sono comandi.": "leaves the field so keys become commands.",
  "Configurazione": "Settings",
  "chiudi": "close",
  "Configurazione servizi": "Service settings",
  "Testo": "Text",
  "Immagini": "Images",
  "Chiavi API:": "API keys:",
  "Chiave API": "API key",
  "Modello": "Model",
  "URL base": "Base URL",
  "Servizio attivo": "Active service",
  "Simulato": "Mock",
  "Modello locale": "Local model",
  "Letta da .env.local (solo in sviluppo). ": "Loaded from .env.local (development only). ",
  "Salvata cifrata nel portachiavi del sistema. ": "Saved encrypted in the system keychain. ",
  "Resta in questa scheda e non viene salvata. ": "Kept in this tab only and not saved. ",
  "Su questo sistema non c'è un portachiavi: resta in memoria finché l'app è aperta. ": "No keychain is available on this system: kept in memory while the app is open. ",
  "testo del capitolo": "chapter script",
  "chi fa lo spoglio": "breakdown service",
  "Euristica deterministica, nessun modello: è il livello di riferimento da battere": "Deterministic heuristic, no model: the baseline to beat",
  "API di Anthropic: il modello più capace, ma il copione esce verso terzi": "Anthropic API: the most capable model, but the script is sent to a third party",
  "API di DeepSeek: JSON garantito ma non lo schema — lo controlla la validazione a valle": "DeepSeek API: guarantees JSON, not the schema; validated afterwards",
  "API di OpenAI: risposta vincolata allo schema, ma il copione esce verso terzi": "OpenAI API: schema-constrained output, but the script is sent to a third party",
  "Un Ollama che hai già installato: il copione non esce dalla macchina": "Your existing Ollama installation: the script stays on your computer",
  "Il modello installato dalla procedura guidata dei modelli locali: il copione non esce dal computer": "The model installed by the local models wizard: the script stays on your computer",
  "modello": "model",
  "chiave API": "API key",
  "host": "host",
  "Il copione esce verso terzi": "The script is sent to a third party",
  "Il copione esce verso terzi.": "The script is sent to a third party.",
  ", e ogni immagine si paga.": ", and each image is billed.",
  "DeepSeek garantisce JSON valido ma non la forma richiesta: gli scostamenti li intercetta la validazione, e compaiono qui sotto.": "DeepSeek guarantees valid JSON, not the required structure: validation catches discrepancies and lists them below.",
  "La richiesta parte dal": "The request comes from the",
  ", non dal server che serve questa pagina: vale quindi il": ", not the server hosting this page, so the relevant host is",
  "della tua macchina. Se Ollama rifiuta, riavvialo con": "on your computer. If Ollama refuses, restart it with",
  "Spoglia il capitolo": "Break down chapter",
  "Spoglio in coda…": "Breakdown queued…",
  "Spoglio in corso…": "Breaking down…",
  "Comincio…": "Starting…",
  "Individuo le scene…": "Identifying scenes…",
  "Spoglio… parte {0} di {1}": "Breakdown… part {0} of {1}",
  "Spoglio… scena {0} di {1}": "Breakdown… scene {0} of {1}",
  "Titoli markdown o righe": "Markdown headings or lines",
  "dividono le scene; i paragrafi diventano beat; le battute si scrivono": "separate scenes; paragraphs become beats; write dialogue as",
  "NOME: testo": "NAME: text",
  "scene ·": "scenes ·",
  "beat ·": "beats ·",
  "pagine —": "pages —",
  "vignette": "panels",
  "regole della serie": "series rules",
  "Valgono per ogni capitolo. Per esempio:\nDialoghi brevi, al massimo due battute per vignetta.\nSara non dice mai parolacce; Elio parla in dialetto.\nLe scene al faro si aprono sempre con un campo lungo.": "Apply to every chapter. For example:\nKeep dialogue short, at most two lines per panel.\nSara never swears; Elio speaks in dialect.\nLighthouse scenes always open with a long shot.",
  "imparato dalle revisioni": "learned from revisions",
  "Allo spoglio arrivano anche": "Breakdown also receives",
  "personaggi (": "characters (",
  "con scheda: aspetto e costumi),": "with sheets: appearance and costumes),",
  "luoghi già visti": "previous locations",
  "cosa riceve il modello": "model input",
  "nascondi cosa riceve il modello": "hide model input",
  "istruzioni di sistema": "system instructions",
  "il copione": "the script",
  "+ capitolo": "+ chapter",
  "Aggiungi un capitolo all'opera": "Add a chapter to the project",
  "titolo del capitolo": "chapter title",
  "Sposta il capitolo prima del precedente: i numeri seguono (Alt+↑ sul capitolo)": "Move the chapter before the previous one; renumber automatically (Alt+↑ on chapter)",
  "Sposta il capitolo dopo il successivo: i numeri seguono (Alt+↓ sul capitolo)": "Move the chapter after the next one; renumber automatically (Alt+↓ on chapter)",
  "Elimina il capitolo dall'opera (Canc sul capitolo)": "Delete the chapter from the project (Delete on chapter)",
  "Eliminare il capitolo {0} «{1}»?": "Delete chapter {0} “{1}”?",
  "Se ne vanno {0}.": "This removes {0}.",
  "Le sue {0} regole «vale per la serie» passano fra le regole della serie.": "Its {0} series-wide rules will move to the series rules.",
  "La sua regola «vale per la serie» passa fra le regole della serie.": "Its series-wide rule will move to the series rules.",
  "Un'opera ha almeno un capitolo": "A project must have at least one chapter",
  "le sue {0} pagine": "its {0} pages",
  "{0} revisioni": "{0} revisions",
  "Riferimenti dell'opera": "Project references",
  "Stile": "Style",
  "Personaggi": "Characters",
  "Luoghi": "Locations",
  "Come è disegnata l'opera: il testo e le tavole di stile": "How the comic is drawn: description and style references",
  "Le schede dei personaggi": "Character sheets",
  "Le schede dei luoghi: com'è fatto ogni posto in cui si svolge una scena": "Location sheets: the appearance of each scene's setting",
  "come è disegnata l'opera": "comic art style",
  "Uno per tutta l'opera: va in testa a ogni immagine, uguale, e le sue tavole si allegano a ogni generazione.": "One style for the entire comic: prepended to every image prompt, with references attached to each generation.",
  "Nessuno stile scelto: finché non lo scrivi vale «": "No style selected: until you specify one, the default is “",
  "Nessuno stile scelto per l'opera: si usa «": "No style selected for the comic: using “",
  "», perché un'opera senza stile esce come un collage.": "”, because a comic without a style looks like a collage.",
  "sistema": "system",
  "sistema " : "system ",
  "scegli lo stile": "choose a style",
  "Un clic scrive lo stile qui sotto: è un punto di partenza, correggilo finché somiglia a ciò che vuoi. Ctrl+Z torna a quello di prima.": "Click to fill in a starting style, then adjust it to match your vision. Ctrl+Z restores the previous style.",
  "stile (vale per ogni immagine dell'opera)": "style (applies to every image in the comic)",
  "Il segno, il colore, l'ombreggiatura, la texture: in inglese il modello lo legge meglio. Dillo in positivo («hand-drawn», «flat colours») invece di elencare ciò che non vuoi.": "Linework, colour, shading, texture: models understand English best. Use positive descriptions (“hand-drawn”, “flat colours”) instead of listing what you do not want.",
  "tavole di stile": "style references",
  "tavola di stile": "style reference",
  "Un'immagine che ha già il segno giusto vale più di qualunque descrizione: si allega a ogni vignetta, scheda e tavola di luogo, e il modello ne copia linea, colore e ombre — non il soggetto. La più semplice da avere: genera una vignetta, e se ti convince tienila come tavola di stile dalla scheda Arte.": "An image with the right style is worth more than a description: attached to every panel, character sheet and location reference, it guides linework, colour and shading, not the subject. Generate a panel you like and keep it as a style reference from the Artwork tab.",
  "Nessuna tavola di stile: il segno può variare da una vignetta all'altra. Quando una vignetta ti convince, tienila come tavola di stile qui sotto.": "No style references: artwork may vary between panels. Keep a panel you like as a style reference below.",
  "Si allegherà a ogni generazione dell'opera: il modello ne copia il segno, non il contenuto": "Attach to every generation: the model copies the style, not the content",
  "Se allegarla a ogni generazione: il modello ne copia il segno, non il contenuto. Se ne allegano al massimo {0}.": "Attach to each generation: the model copies the style, not the content. At most {0} references are attached.",
  "Sono dell'opera, non del capitolo: com'è fatto ognuno si dice qui una volta, e vale in ogni vignetta.": "Characters belong to the comic, not a chapter: define their appearance once for every panel.",
  "Nessun personaggio: arrivano dallo spoglio del copione.": "No characters yet: script breakdown creates them.",
  "nome nella storia": "name in the story",
  "chi è (per te, non entra nelle istruzioni)": "who they are (for you, not included in prompts)",
  "com'è fatto": "appearance",
  "L'aspetto va nelle istruzioni per i modelli: in inglese rende meglio, ma l'italiano funziona.": "Appearance is included in model prompts: English works best, but Italian also works.",
  "età e genere": "age and gender",
  "corpo": "build",
  "capelli": "hair",
  "occhi": "eyes",
  "viso": "face",
  "pelle": "skin",
  "segni particolari": "distinctive features",
  "costumi": "costumes",
  "+ costume": "+ costume",
  "costume": "costume",
  "nome": "name",
  "notte, divisa…": "night, uniform…",
  "immagini di riferimento": "reference images",
  "La scheda generata parte dall'aspetto scritto sopra e dalle tavole di stile dell'opera; ogni vista guarda quelle già spuntate, quindi tieni la prima che ti convince e genera le altre da lì. Quelle spuntate si allegano da sole quando generi una vignetta in cui compare: è ciò che lo tiene uguale da una all'altra. Bastano due o tre buone — fronte, tre quarti, figura intera.": "The generated sheet uses the appearance above and the comic's style references. Each view uses selected images, so keep a good first view and build from it. Selected references are attached automatically to panels featuring this character. Two or three good views are enough: front, three-quarter and full body.",
  "Se allegarla al modello quando si genera: tieni solo quelle in cui il personaggio è proprio lui": "Attach when generating: keep only references that accurately portray the character",
  "Si allegherà alle vignette in cui compare": "Attach to panels featuring this character",
  "Genera la scheda (3 viste)": "Generate character sheet (3 views)",
  "Fronte, tre quarti e figura intera, dall'aspetto scritto qui sopra e nello stile dell'opera": "Front, three-quarter and full body, using the appearance above and the comic's style",
  "Per generare la scheda serve almeno un campo dell'aspetto: è da lì che il modello lo disegna.": "Fill in at least one appearance field to generate the character sheet.",
  "Per generare serve il servizio di immagini configurato: Pagine → Arte → «servizio e spesa».": "Configure an image service to generate: Pages → Artwork → “service and cost”.",
  "genera la scheda": "generate sheet",
  "Riferimenti personaggio in coda": "Character references queued",
  "Personaggio {0} · {1}": "Character {0} · {1}",
  "La scheda personaggio e' cambiata. Rilancia la generazione.": "The character sheet changed. Generate again.",
  "La scheda personaggio e' cambiata durante la generazione.": "The character sheet changed during generation.",
  "{0} {1} ai riferimenti{2}. Togli la spunta a quelle che non gli somigliano.": "{0} {1} to references{2}. Deselect images that do not resemble the character.",
  "rinomina un personaggio": "rename a character",
  "nuovo nome": "new name",
  "Cambia chi parla e chi è in vignetta in tutto il progetto. Il nome dentro le battute si cambia con trova e sostituisci.": "Update speakers and panel characters throughout the project. Use find and replace to change names within dialogue.",
  "Rinomina": "Rename",
  "{0} ora si chiama {1}.": "{0} is now named {1}.",
  "togli la scheda": "remove sheet",
  "Toglie la scheda; il personaggio resta nei pannelli": "Remove the sheet; keep the character in panels",
  "Le scene dicono dove siamo; qui si dice com'è fatto il posto, perché sia lo stesso posto in ogni vignetta.": "Scenes define where we are; define what the place looks like here to keep it consistent across panels.",
  "Nessun luogo: arrivano dallo spoglio del copione, dal nome che ogni scena dà al posto in cui si svolge.": "No locations yet: breakdown creates them from each scene's setting.",
  "Proponi le descrizioni che mancano (": "Suggest missing descriptions (",
  "Dalle scene ambientate lì e dalle regole della serie": "Based on scenes set there and series rules",
  "Descrizioni dei luoghi in coda": "Location descriptions queued",
  "{0} descrizioni · {1}": "{0} descriptions · {1}",
  "Descrizioni proposte per {0}: rileggile, sono il punto di partenza. Ctrl+Z le toglie.": "Descriptions suggested for {0}: review them as a starting point. Ctrl+Z removes them.",
  "propongo {0} descrizioni…": "suggesting {0} descriptions…",
  "Il modello non ha proposto niente: scrivi la descrizione a mano.": "The model suggested nothing: write the description manually.",
  "descrivilo": "describe it",
  "Pianta, arredi e dove stanno, materiali, colori, da dove viene la luce. L'ora no: è della scena. Va in ogni vignetta ambientata qui, parola per parola.": "Layout, furniture and placement, materials, colours, light sources. Time of day belongs to the scene. This description goes into every panel set here, word for word.",
  "colori del luogo": "location colours",
  "Proponi una descrizione ·": "Suggest a description ·",
  "Dalle scene ambientate qui e dalle regole della serie; solo se la descrizione è vuota": "Based on scenes set here and series rules; only if the description is empty",
  "propongo la descrizione…": "suggesting a description…",
  "immagini del luogo": "location references",
  "Una o due tavole bastano, anche da punti di vista diversi: la seconda guarda la prima, e resta lo stesso posto. Va bene anche una vignetta riuscita, tenuta come riferimento del luogo dalla scheda Arte.": "One or two references are enough, even from different viewpoints: the second uses the first to keep the same location. You can also keep a good panel as a location reference from the Artwork tab.",
  "Si allegherà alle vignette ambientate lì": "Attach to panels set here",
  "Se allegarla alle vignette ambientate qui: il modello ne prende pianta, arredi e materiali, non l'inquadratura": "Attach to panels set here: the model uses layout, furniture and materials, not the framing",
  "Genera una tavola del luogo": "Generate location reference",
  "Il luogo vuoto, visto largo, nello stile dell'opera; le immagini già spuntate qui lo tengono lo stesso posto": "An empty wide view in the comic's style; selected images keep the location consistent",
  "Per generare la tavola serve la descrizione: è da lì che il modello disegna il posto.": "Add a description to generate the location reference.",
  "Tavola del luogo in coda": "Location reference queued",
  "Luogo {0} · {1}": "Location {0} · {1}",
  "La descrizione del luogo e' cambiata durante la generazione.": "The location description changed during generation.",
  "Tavola aggiunta{0}. Se non è il posto giusto togli la spunta e generane un'altra; se lo è, ogni vignetta ambientata qui la riceverà.": "Reference added{0}. Deselect and regenerate if it is not the right place; otherwise, it will be attached to every panel set here.",
  "genero la tavola del luogo…": "generating location reference…",
  "genera la tavola": "generate reference",
  "Toglie la scheda; le scene restano ambientate lì": "Remove the sheet; scenes keep this setting",
  "Nessuna scena è ambientata qui.": "No scenes are set here.",
  "scena «": "scene “",
  "né descrizione né immagini: ogni vignetta lo reinventa": "no description or images: each panel reinvents it",
  "descritto, con immagini": "described, with images",
  "scheda incompleta": "incomplete sheet",
  "scheda completa": "complete sheet",
  "senza scheda": "no sheet",
  "aggiungi un personaggio…": "add a character…",
  "in vignetta": "in panel",
  "espressione": "expression",
  "tesa, sollevata…": "tense, relieved…",
  "Solo le voci di": "Only entries from",
  "Nessuno: un luogo, un oggetto, un paesaggio.": "None: a location, an object, a landscape.",
  "Sostituisci l'immagine…": "Replace image…",
  "+ immagine…": "+ image…",
  "Carica immagine…": "Upload image…",
  "togli": "remove",
  "immagine aggiunta": "image added",
  "immagini aggiunte": "images added",
  "Ne sono spuntate": "Selected references:",
  ": si allegano le prime": ": the first ones attached are",
  ", per lasciare posto a luoghi e personaggi.": ", leaving room for locations and characters.",
  "{0} {1} di stile": "{0} {1} for style",
  "{0} del luogo": "{0} for the location",
  "{0} delle immagini di {1}": "{0} of {1}'s images",
  "dallo stile dell'opera": "from the comic's style",
  "dalla scheda del luogo": "from the location sheet",
  "dalla scheda del personaggio": "from the character sheet",
  "immagine di «": "image of “",
  "Per chi disegna è la specifica della vignetta, non una nota.": "For the artist, this is the panel specification, not a note.",
  "Vignetta": "Panel",
  "Balloon": "Balloon",
  "Arte": "Artwork",
  "Pagina": "Page",
  "Pagina:": "Page:",
  "Pagina {0}": "Page {0}",
  "Pagina {0}{1}": "Page {0}{1}",
  "pagina {0}": "page {0}",
  "Pagina {0} · {1} vignette · {2}": "Page {0} · {1} panels · {2}",
  "Azione, inquadratura, griglia, personaggi": "Action, camera, grid, characters",
  "Testi, posizione e coda": "Text, placement and tails",
  "Immagine della vignetta, generazione e istruzioni per un modello esterno": "Panel image, generation and external model instructions",
  "Cosa si modifica della vignetta": "Panel editing mode",
  "Aggiungi una pagina": "Add a page",
  "Scegli il lay-out della pagina nuova (dopo la": "Choose the new page's layout (after page",
  "Due pannelli affiancati": "Two panels side by side",
  "Due pannelli uno sopra l'altro": "Two stacked panels",
  "Sposta la pagina prima (Alt+← sulla miniatura)": "Move page earlier (Alt+← on thumbnail)",
  "Sposta la pagina dopo (Alt+→ sulla miniatura)": "Move page later (Alt+→ on thumbnail)",
  "Elimina la pagina (Canc sulla miniatura)": "Delete page (Delete on thumbnail)",
  "← prima": "← earlier",
  "↑ prima": "↑ earlier",
  "dopo →": "later →",
  "dopo ↓": "later ↓",
  "elimina": "delete",
  "azione": "action",
  "camera completa": "full camera settings",
  "inquadratura rapida": "quick camera settings",
  "griglia": "grid",
  "⊟ dividi in orizzontale": "⊟ split horizontally",
  "◫ dividi in verticale": "◫ split vertically",
  "unisci a": "merge with",
  "Unisci con {0}": "Merge with {0}",
  "Nessun vicino con cui formare un rettangolo: niente da unire.": "No adjacent panel forms a rectangle: nothing to merge.",
  "inquadratura": "shot",
  "angolo": "angle",
  "focale (mm)": "focal length (mm)",
  "profondità di campo": "depth of field",
  "luce": "lighting",
  "tono": "mood",
  "movimento": "motion",
  "soggetto": "subject placement",
  "asse di scena": "scene axis",
  "campo lunghissimo": "extreme long shot",
  "campo lungo": "long shot",
  "figura intera": "full shot",
  "piano americano": "cowboy shot",
  "campo medio": "medium shot",
  "mezzo busto": "medium close-up",
  "mezzoprimo piano": "medium close-up",
  "primo piano": "close-up",
  "primissimo piano": "extreme close-up",
  "dal basso": "low angle",
  "dall'alto": "high angle",
  "a picco": "overhead",
  "inquadratura ad altezza occhi": "eye-level shot",
  "Questa vignetta non ha balloon.": "This panel has no balloons.",
  "Nuovo balloon": "New balloon",
  "Nuovo balloon nella vignetta, e lo scrivi subito": "Add a balloon to the panel and start typing",
  "Elimina il balloon": "Delete balloon",
  "+ balloon": "+ balloon",
  "togli battuta": "remove dialogue",
  "tipo di battuta": "dialogue type",
  "chi parla": "speaker",
  "testo": "text",
  "posizione e coda, in numeri": "position and tail coordinates",
  "coda x": "tail x",
  "coda y": "tail y",
  "segue la pagina principale: spostarlo qui vale solo per questo formato.": "follows the main page: moving it here affects only this format.",
  "ha una posizione sua.": "has its own position.",
  "reimposta": "reset",
  "Formato mostrato": "Displayed format",
  "Digitale": "Digital",
  "Stampa B5": "Print B5",
  "Striscia": "Strip",
  "formato principale: qui si ritocca tutto": "main format: edit everything here",
  "qui si spostano solo i balloon, per questo formato": "move balloons for this format only",
  "In {0} si spostano solo i balloon, e solo per questo formato. Griglia e vignette si ritoccano sul formato principale.": "In {0}, only balloon positions can be edited, for this format only. Edit the grid and panels in the main format.",
  "Dimensione della pagina": "Page size",
  "intera": "fit page",
  "larga": "fit width",
  "La pagina intera, sempre in vista": "Keep the entire page visible",
  "Larga quanto la colonna: più grande, si scorre": "Fit the column width; scroll to see the rest",
  "Carico il font…": "Loading font…",
  "Font non caricato:": "Font not loaded:",
  "Nessuna anteprima: il lay-out non è in modalità \"page\".": "No preview: layout is not in “page” mode.",
  "Mostra l'ultima versione valida: le modifiche non valide non sono applicate.": "Showing the last valid version: invalid changes are not applied.",
  "Trascina balloon, punta della coda e gutter · trascina un'immagine su una vignetta per dargliela · Ctrl+Z annulla · ? per le scorciatoie.": "Drag balloons, tails and gutters · drop an image onto a panel · Ctrl+Z to undo · ? for shortcuts.",
  "Pagina: frecce per le vignette, Invio per i balloon, ? per tutte le scorciatoie": "Page: arrows for panels, Enter for balloons, ? for all shortcuts",
  "Trascina la punta della coda verso chi parla": "Drag the tail tip towards the speaker",
  "Trascina per spostare il gutter": "Drag to move the gutter",
  "{0}: trascina per spostare{1}{2}": "{0}: drag to move{1}{2}",
  "Area Pagine": "Pages area",
  "Pagina precedente / successiva": "Previous / next page",
  "Prima / ultima pagina": "First / last page",
  "Vignetta vicina": "Adjacent panel",
  "Entra nei balloon della vignetta": "Enter the panel's balloons",
  "Scheda Vignetta: scrivi l'azione": "Panel tab: edit the action",
  "Scheda Balloon": "Balloon tab",
  "Scheda Arte": "Artwork tab",
  "Pagina ↔ striscia": "Page ↔ strip",
  "Inquadra l'immagine della vignetta (tua o generata)": "Frame the panel image (uploaded or generated)",
  "Con un balloon scelto": "With a balloon selected",
  "Sposta il balloon": "Move balloon",
  "Lo sposta a passi grandi": "Move in large steps",
  "Sposta la punta della coda": "Move the tail tip",
  "Corpo del testo più grande / più piccolo": "Increase / decrease font size",
  "Balloon successivo / precedente": "Next / previous balloon",
  "Scrive nel testo del balloon": "Edit balloon text",
  "Torna alla vignetta": "Return to panel",
  "Inquadratura dell'immagine": "Image framing",
  "Sposta l'immagine nella vignetta": "Move image within panel",
  "La sposta a passi grandi": "Move in large steps",
  "Inquadratura più stretta / più larga": "Zoom in / out",
  "Torna centrata, a misura": "Reset position and scale",
  "Fine inquadratura": "Finish framing",
  "Inquadra sulla pagina": "Frame on page",
  "Sulla pagina: trascina o frecce per spostare, rotella o + − per ingrandire (I)": "On the page: drag or use arrows to move, wheel or + − to zoom (I)",
  "Sulla pagina: trascina dentro il pannello (o frecce) per spostare l'immagine, rotella (o + −) per ingrandire, Esc per finire.": "On the page: drag within the panel (or use arrows) to move, wheel (or + −) to zoom, Esc to finish.",
  "Inquadratura dell'immagine: trascina o frecce per spostarla, rotella o + − per ingrandirla, 0 la ricentra, Esc per finire.": "Image framing: drag or use arrows to move, wheel or + − to zoom, 0 to reset, Esc to finish.",
  "Trascina (o frecce) per spostare l'immagine, rotella (o + −) per ingrandire, Esc per finire": "Drag (or use arrows) to move, wheel (or + −) to zoom, Esc to finish",
  "L'inquadratura è di questa immagine: una rigenerata riparte centrata, e Ctrl+Z riporta quella di prima con la sua.": "Framing belongs to this image: regenerated images start centred; Ctrl+Z restores the previous image and its framing.",
  "Taglio dell'inquadratura": "Image fit",
  "riempie": "fill",
  "adatta": "contain",
  "L'immagine riempie il pannello: i bordi in più si tagliano": "Fill the panel, cropping overflow",
  "L'immagine si vede intera: dove non arriva resta il fondo": "Show the whole image, with background in any unused space",
  "Carica un'immagine, oppure trascinala sul pannello nella pagina.": "Upload an image or drop it onto a panel on the page.",
  "Carica da file…": "Upload from file…",
  "Il file resta in art/: si scollega solo dal pannello": "The file remains in art/: only the panel link is removed",
  "scollega": "unlink",
  "a mano": "uploaded",
  "generata": "generated",
  "poi modificata": "modified since",
  "mai generata": "never generated",
  "da rigenerare: la vignetta è cambiata dopo il render": "outdated: the panel changed after rendering",
  "file non trovato nella cartella": "file not found in folder",
  "Il file del render non c'è più: rigenera la vignetta.": "The render file is missing: regenerate the panel.",
  "è venuto bene? tienilo come": "Like the result? Keep it as",
  "Tenuta come tavola di stile: da ora si allega a ogni generazione dell'opera, e tutte le vignette risultano da rigenerare.": "Kept as a style reference: now attached to every generation; all panels are marked as outdated.",
  "Tenuta come riferimento di {0}. Le vignette in cui compare risultano da rigenerare: ora hanno un riferimento in più.": "Kept as a reference for {0}. Panels featuring this character are now outdated: they have a new reference.",
  "Tenuta come immagine di «{0}»: le vignette ambientate lì risultano da rigenerare, ora hanno il posto da guardare.": "Kept as a reference for “{0}”: panels set there are now outdated, with a new location reference.",
  "genera l'arte": "generate artwork",
  "Genera la vignetta": "Generate panel",
  "Genera la pagina": "Generate page",
  "Generazione interrotta.": "Generation stopped.",
  "Generazione annullata.": "Generation cancelled.",
  "Genero": "Generating",
  "Genero…": "Generating…",
  "Altra variante": "Another variation",
  "Stessa vignetta con un altro seed; quella di prima resta in renders/": "Same panel, different seed; the previous image remains in renders/",
  "Niente da generare": "Nothing to generate",
  "Interrompi": "Stop",
  "annulla": "cancel",
  "in coda": "queued",
  "In coda": "Queued",
  "In coda · posizione {0}": "Queued · position {0}",
  "in lavorazione": "processing",
  "In esecuzione": "Running",
  "in esecuzione,": "running,",
  "Le vignette della pagina senza arte tua e senza un render aggiornato": "Page panels without uploaded artwork or an up-to-date render",
  "Ha arte tua collegata, e quella vince: il render si vedrà solo scollegandola.": "Uploaded artwork takes priority: unlink it to display the render.",
  "Il seed deriva dal seed di serie e dal pannello: stesso pannello, stesso seed. Le proporzioni vengono dal box del pannello nel formato mostrato.": "The seed comes from the series seed and panel: same panel, same seed. Aspect ratio follows the panel box in the displayed format.",
  "Si genera sul formato principale (": "Generation uses the main format (",
  "): le proporzioni della vignetta vengono da lì, e gli altri formati riusano la stessa immagine.": "): panel proportions come from it, and other formats reuse the image.",
  "servizio e spesa": "service and cost",
  "servizio": "service",
  "servizio di prova": "mock service",
  "prova, senza rete né spesa (immagine grigia)": "test without network or cost (grey image)",
  "tetto di spesa per lancio ($)": "spending limit per run ($)",
  "risoluzione": "resolution",
  "1 megapixel": "1 megapixel",
  "2 megapixel (costa di più)": "2 megapixels (higher cost)",
  "La spesa mostrata è una stima sul listino noto; quella vera la dichiara il fornitore a immagine fatta.": "Displayed cost is an estimate from known pricing; the provider reports the actual charge after generation.",
  "Prompt e riferimenti escono verso terzi": "Prompts and references are sent to a third party",
  "Cambiarlo rende «da rigenerare» le vignette fatte con l'altro; i loro file restano in renders/, e tornando indietro si ritrovano senza spesa.": "Changing models marks previous panels as outdated; files stay in renders/ and switching back reuses them at no cost.",
  "La stima ({0}) supera il tetto di spesa ({1}): alzalo qui sotto, o genera meno vignette.": "Estimated cost ({0}) exceeds the spending limit ({1}): raise it below or generate fewer panels.",
  "Serve la chiave API di Black Forest Labs": "A Black Forest Labs API key is required",
  "Servono endpoint e chiave della risorsa Azure AI Foundry": "An Azure AI Foundry resource endpoint and key are required",
  "Serve l'indirizzo del motore locale, su questa macchina (http://127.0.0.1:porta)": "Enter the local engine address on this computer (http://127.0.0.1:port)",
  "Il modello locale delle immagini non è ancora installato (Progetto → Modelli locali…)": "The local image model is not installed yet (Project → Local models…)",
  "FLUX.2 [klein] 4B — in locale, sulla tua GPU": "FLUX.2 [klein] 4B — locally, on your GPU",
  "Quattro immagini di riferimento al massimo per vignetta (una di stile, una del luogo, il resto ai personaggi). Il modello è molto più piccolo di [pro]: buono per provare inquadrature e pagine, da confrontare con [pro] prima di fidarsene.": "At most four references per panel (one style, one location, the rest for characters). Much smaller than [pro]: useful for testing framing and pages; compare with [pro] before relying on it.",
  "sd-server di stable-diffusion.cpp, avviato su questa macchina con FLUX.2 [klein] 4B, il suo text encoder (Qwen3 4B) e il VAE di FLUX.2. Niente si paga e niente esce dal computer; serve una GPU con 8–13 GB di memoria, o un Mac con Apple Silicon. Nell'app desktop lo installa e lo avvia la procedura guidata.": "stable-diffusion.cpp's sd-server running on this computer with FLUX.2 [klein] 4B, its Qwen3 4B text encoder and FLUX.2 VAE. No cost, and nothing leaves your computer; requires a GPU with 8–13 GB of memory or an Apple Silicon Mac. The desktop wizard installs and starts it.",
  "indirizzo del motore": "engine address",
  "chiave di api.bfl.ai": "api.bfl.ai key",
  "chiave della risorsa": "resource key",
  "endpoint della risorsa": "resource endpoint",
  "nome del deployment": "deployment name",
  "Va bene anche l'endpoint del progetto (…/api/projects/nome): se ne usa l'indirizzo della risorsa.": "The project endpoint (…/api/projects/name) also works: its resource address is used.",
  "Il modello si riconosce da qui: [flex] se il nome contiene «flex», altrimenti [pro]. Il deployment ha un limite di richieste al minuto: una pagina intera può fermarsi ad aspettare, ed è normale.": "The model is identified by name: [flex] if it contains “flex”, otherwise [pro]. Deployments limit requests per minute: generating a whole page may pause to wait.",
  "Verifica il motore": "Check engine",
  "Verifica in coda…": "Check queued…",
  "Verifica {0}": "Check {0}",
  "La vignetta e' cambiata dopo il clic. Rilancia la generazione.": "The panel changed after the click. Generate again.",
  "La vignetta e' cambiata mentre era in coda.": "The panel changed while queued.",
  "Il progetto o il contenuto del lavoro in coda e' cambiato. Rilancia la generazione.": "The project or queued job content changed. Generate again.",
  "Il progetto e' cambiato.": "The project changed.",
  "Questo lavoro e' gia' in coda.": "This job is already queued.",
  "Immagini in coda": "Images queued",
  "{0} fatte, poi: ": "{0} completed, then: ",
  "{0} generate": "{0} generated",
  "{0} ritrovate in renders/ senza spesa": "{0} reused from renders/ at no cost",
  "{0} fallite": "{0} failed",
  "{0} fermate": "{0} stopped",
  " · addebitati {0}": " · charged {0}",
  " · addebitati {0} $": " · charged ${0}",
  "istruzioni per un modello esterno": "external model instructions",
  "Brief e prompt per un modello di immagini esterno, pannello per pannello": "Briefs and prompts for an external image model, panel by panel",
  "Per modelli che seguono istruzioni (ChatGPT, Gemini, Claude con immagini).": "For instruction-following models (ChatGPT, Gemini, Claude with images).",
  "Per modelli di sole immagini (Stable Diffusion, Flux, Midjourney).": "For image-only models (Stable Diffusion, Flux, Midjourney).",
  "Brief del pannello": "Panel brief",
  "Brief della pagina": "Page brief",
  "Copia il brief": "Copy brief",
  "Copia tutta la pagina": "Copy entire page",
  "positivo": "positive",
  "negativo": "negative",
  "Copia il positivo": "Copy positive prompt",
  "Copia il negativo": "Copy negative prompt",
  "Copia i parametri": "Copy parameters",
  "Il browser non consente di copiare qui: seleziona il testo e copia a mano.": "The browser cannot copy here: select the text and copy manually.",
  "{0} copiato": "{0} copied",
  "FLUX.2 non ha un prompt negativo: ciò che scrivi qui finisce nominato nel prompt, e a volte compare proprio per questo.": "FLUX.2 has no negative prompt: anything written here is mentioned in the prompt and may appear because of that.",
  "Immagini allegate:": "Attached images:",
  "Nelle istruzioni:": "In the prompt:",
  "prompt personale": "custom prompt",
  "prompt tuo per questo pannello (sostituisce quello compilato)": "custom prompt for this panel (replaces the compiled prompt)",
  "vuoto: si usa il prompt compilato dalle scelte dell'editor": "empty: use the prompt compiled from editor settings",
  "da evitare": "avoid",
  "lascialo vuoto, se puoi": "leave empty if possible",
  "Cosa c'è da rivedere": "Items to review",
  "Cosa c'è da rivedere: ritmo, layout, inquadrature, disegno…": "Items to review: pacing, layout, framing, artwork…",
  "Validazione": "Validation",
  "Cosa segnala il controllo, pagina per pagina. Un clic porta alla pagina.": "Validation findings, page by page. Click to open a page.",
  "Nessun problema — documento valido.": "No issues — valid document.",
  "nessun problema": "no issues",
  "{0} scene": "{0} scenes",
  "{0} correzioni aperte": "{0} open corrections",
  "1 correzione aperta": "1 open correction",
  "1 revisione aperta": "1 open revision",
  "{0} revisioni aperte": "{0} open revisions",
  " · {0} revisioni aperte": " · {0} open revisions",
  "1 scena": "1 scene",
  "correzioni": "corrections",
  "trova e sostituisci": "find and replace",
  "scambio con lo sceneggiatore": "writer review",
  "Una vignetta o una battuta si annotano dall'editor, con «annota…».": "Add notes to a panel or dialogue from the editor using “annotate…”.",
  "nuova nota": "new note",
  "revisioni aperte (": "open revisions (",
  "Nessuna revisione in attesa.": "No pending revisions.",
  "nessuna correzione aperta": "no open corrections",
  "Rifiuta tutte": "Reject all",
  "Accetta le applicabili (": "Accept applicable (",
  "Accetta": "Accept",
  "Accetta (per una nota: fatta…)": "Accept (for a note: done…)",
  "Fatta…": "Done…",
  "Applica comunque": "Apply anyway",
  "Sovrascrive ciò che c'è ora; il changelog registra cosa c'era": "Overwrite the current text; the changelog records the previous version",
  ". Accettare una correzione riscrive solo i balloon coinvolti.": ". Accepting a correction rewrites only the affected balloons.",
  "Non applicabile:": "Not applicable:",
  "Il copione cambia qui, ma non c'è una battuta da aggiornare con certezza (prosa, o una battuta già diversa nel fumetto): decidi tu cosa toccare.": "The script changes here, but no dialogue can be confidently updated (prose, or dialogue already different in the comic): decide what to edit.",
  "La battuta": "Dialogue",
  "la battuta": "dialogue",
  "la vignetta": "panel",
  "la pagina": "page",
  "la sua pagina": "its page",
  "questa scheda": "this tab",
  "una revisione": "a revision",
  "regola per la serie: «": "series rule: “",
  "con motivo": "with reason",
  "cosa hai fatto (facoltativo)": "what you did (optional)",
  "perché (facoltativo)": "why (optional)",
  "corretto da": "corrected by",
  "in vigore": "active",
  "testo proposto": "proposed text",
  "Va alla vignetta": "Go to panel",
  "mostra tutto il capitolo": "show entire chapter",
  "storico: {0} applicate, {1} rifiutate": "history: {0} accepted, {1} rejected",
  "nascondi lo storico": "hide history",
  "ripristina": "restore",
  "riapri": "reopen",
  "Torna al testo di prima, con una correzione inversa nel changelog": "Restore the previous text, recording a reverse correction in the changelog",
  "Applicata sopra un testo diverso da quello atteso: «": "Applied over text that differed from the expected text: “",
  "{0} correzioni applicate: {1} battute riletterate, il resto della pagina non si tocca.": "{0} corrections applied: {1} dialogue balloons relettered; the rest of the page is unchanged.",
  "Esporta per la revisione (.md)": "Export for review (.md)",
  "Importa il file corretto…": "Import corrected file…",
  "file corretto": "corrected file",
  "Nessuna differenza nel file: niente da correggere.": "No differences in the file: nothing to correct.",
  "File per lo sceneggiatore esportato ({0}). Te lo rimanda corretto: lo reimporti qui.": "Writer review file exported ({0}). Import the corrected version here when it comes back.",
  "{0} correzioni importate da «{1}». Accettale o rifiutale qui sotto.{2}": "{0} corrections imported from “{1}”. Accept or reject them below.{2}",
  "Niente di nuovo in «{0}».{1}": "Nothing new in “{0}”.{1}",
  "{0} già in attesa": "{0} already pending",
  "{0} già rifiutate, non riproposte (si riaprono dallo storico)": "{0} already rejected, not proposed again (reopen from history)",
  "nuova versione del copione": "new script version",
  "Incolla qui il capitolo come lo rimanda lo sceneggiatore…": "Paste the chapter returned by the writer…",
  "Questo capitolo non ha ancora un copione di riferimento: il confronto vedrà tutto come nuovo.": "This chapter has no reference script yet: comparison will treat everything as new.",
  "Confronta": "Compare",
  "Nessuna differenza dal copione di riferimento.": "No differences from the reference script.",
  "parti cambiate ·": "changed parts ·",
  "pannelli toccati": "affected panels",
  " · {0} parti nuove fuori da ogni pannello, da impaginare": " · {0} new parts outside any panel, needing layout",
  "Importa le correzioni e adotta questo copione": "Import corrections and adopt this script",
  "Copione aggiornato: {0} pannelli toccati, {1} correzioni da decidere.": "Script updated: {0} affected panels, {1} corrections to review.",
  "trova": "find",
  "sostituisci con": "replace with",
  "maiuscole": "case sensitive",
  "parola intera": "whole word",
  "anche nelle azioni": "include actions",
  "Nessuna occorrenza.": "No matches.",
  "{0} occorrenze in {1} testi.": "{0} matches in {1} texts.",
  "Sostituisci tutto": "Replace all",
  "«{0}» → «{1}» in {2} testi, ognuno tracciato nel changelog.": "“{0}” → “{1}” in {2} texts, each recorded in the changelog.",
  "regola per la serie: vale per ogni capitolo": "series rule: applies to every chapter",
  "vale per la serie…": "apply to series…",
  "Salva la regola": "Save rule",
  "Regola aggiunta alla serie: arriva allo spoglio di ogni capitolo (la vedi in Copione, «cosa riceve il modello»).": "Series rule added: included in every chapter's breakdown (Script → “model input”).",
  "Revisioni, su una voce aperta": "Revisions, with an open entry",
  "annota {0}…": "annotate {0}…",
  "Aggiungi la nota": "Add note",
  "Aggiungi": "Add",
  "da fare": "to do",
  "Non più nel documento": "No longer in the document",
  "non più nel documento": "no longer in the document",
  "pagina {0} (non c'è più)": "page {0} (removed)",
  "scena {0} (non c'è più)": "scene {0} (removed)",
  "scena «{0}»": "scene “{0}”",
  "Striscia dell'episodio": "Episode strip",
  "segna zone da non tagliare": "mark protected zones",
  "Zona da non tagliare": "Protected zone",
  "Trascina in verticale su un pannello per proteggere una fascia (un volto, un dettaglio). Clic su una zona per toglierla.": "Drag vertically on a panel to protect a band (a face, a detail). Click a zone to remove it.",
  "{0}: trascina per spostarlo nella striscia": "{0}: drag to move within the strip",
  "{0} — la striscia come la leggerà il telefono, con i tagli": "{0} — the strip as seen on a phone, including cuts",
  "larga {0} px · slice ≤ {1} px · {2}": "width {0} px · slice ≤ {1} px · {2}",
  "tagli nei gutter · pagine da controllare": "cuts in gutters · pages to review",
  "nel gutter": "in gutter",
  "dentro un pannello: controlla": "inside a panel: review",
  "attraverso un balloon o una zona protetta": "through a balloon or protected zone",
  "{0} su questa vignetta": "{0} on this panel",
  "da {0}": "from {0}",
  "taglio": "cut",
  "prima di esportare": "before exporting",
  "gate F2.1 superato": "F2.1 gate passed",
  "sopra il 20%: gate F2.1 non superato": "over 20%: F2.1 gate failed",
  "formati — dal progetto, capitolo intero (": "formats — from the project, entire chapter (",
  "pag.)": "pages)",
  "destinazione": "destination",
  "Scegli una cartella…": "Choose a folder…",
  "cartella dei download del browser": "browser downloads folder",
  "Questo browser non consente di scegliere una cartella: tutto finisce nei suoi download, in un unico .zip con una cartella per formato.": "This browser cannot choose folders: everything downloads as a single .zip with a folder per format.",
  "Senza cartella scelta, tutto finisce nei download in un unico .zip, una cartella per formato.": "Without a folder, everything downloads as a single .zip with a folder per format.",
  "Una sottocartella per formato.": "One subfolder per format.",
  "Il capitolo": "Chapter",
  "intero, in tutti i formati scelti, dallo stesso documento.": "in full, in all selected formats, from the same document.",
  "Un PDF multipagina del capitolo, dal formato principale": "A multipage chapter PDF from the main format",
  "Vettoriale della pagina canonica, col font incorporato": "Canonical page vector image with embedded font",
  "Il JSON rieditabile: griglia, balloon, camera come dati": "Editable JSON: grid, balloons and camera as data",
  "Documento JSON": "JSON document",
  "includi la specifica di disegno": "include drawing specification",
  "immagini delle vignette": "panel images",
  "in tutto": "total",
  "mostra": "show",
  "scrivo i file…": "writing files…",
  "Nessun file da esportare.": "No files to export.",
  "Scegli almeno un formato.": "Select at least one format.",
  "PDF: pagina {0} di {1}": "PDF: page {0} of {1}",
  "{0}: preparo…": "{0}: preparing…",
  "{0}, nei download del browser": "{0}, in browser downloads",
  "{0} file in {1}.": "{0} files in {1}.",
  "{0} immagini collegate ai loro pannelli.": "{0} images linked to their panels.",
  "{0} immagini collegate. {1}{2}": "{0} images linked. {1}{2}",
  "«{0}» non ha il nome di un pannello": "“{0}” does not match a panel name",
  "«{0}»: formati accettati PNG, JPEG, WebP. Esporta da lì il file sorgente (PSD, CLIP, KRA).": "“{0}”: accepted formats are PNG, JPEG, WebP. Export the source file (PSD, CLIP, KRA) first.",
  "Leggo le dimensioni dell'immagine…": "Reading image dimensions…",
  " · fuori campo": " · off screen",
  " · grigi": " · greyscale",
  " · bleed {0} mm": " · bleed {0} mm",
  ", gate superato": ", gate passed",
  ", sopra il 20%": ", above 20%",
  "— spenta, un pannello senza arte resta vuoto": "— disabled: a panel without artwork stays empty",
  "Modelli locali": "Local models",
  "modelli locali…": "local models…",
  "Configura i modelli locali": "Configure local models",
  "I modelli locali si installano dall'app desktop: nel browser lo spoglio locale passa da Ollama, e le immagini da un motore avviato a mano.": "Install local models in the desktop app. In the browser, use Ollama for breakdown and a manually started image engine.",
  "I modelli locali si installano dall'app desktop: nel browser scegli Ollama.": "Install local models in the desktop app; in the browser, choose Ollama.",
  "1 di 4 · questo computer": "1 of 4 · this computer",
  "2 di 4 · cosa installare": "2 of 4 · what to install",
  "3 di 4 · scarico": "3 of 4 · download",
  "4 di 4 · prova": "4 of 4 · test",
  "Guardo cosa c'è in questo computer…": "Checking this computer…",
  "memoria": "memory",
  "grafica": "graphics",
  "spazio libero": "free disk space",
  "nessuna GPU riconosciuta": "no GPU detected",
  "non rilevato": "not detected",
  "memoria della scheda grafica": "GPU memory",
  "Non si legge da qui: la trovi nelle informazioni della scheda (Gestione attività → Prestazioni → GPU, su Windows).": "Unavailable here: check your GPU details (Task Manager → Performance → GPU on Windows).",
  "accelerazione": "acceleration",
  "Solo il processore — funziona ovunque, ma lento": "CPU only — works everywhere, but slowly",
  "Metal — la GPU del Mac": "Metal — Mac GPU",
  "Vulkan — la scheda grafica (NVIDIA, AMD, Intel)": "Vulkan — GPU (NVIDIA, AMD, Intel)",
  "consigliata": "recommended",
  "consigliato": "recommended",
  "testo locale": "local text",
  "immagini locali": "local images",
  "motore immagini locale": "local image engine",
  "spoglio del copione": "script breakdown",
  " per lo spoglio": " for breakdown",
  " per le immagini": " for images",
  " per spoglio e immagini": " for breakdown and images",
  "GB di RAM": "GB RAM",
  "GB per i modelli": "GB for models",
  "Da scaricare:": "Download size:",
  "circa": "about",
  " · liberi {0} GB": " · {0} GB free",
  " — con {0} GB è al limite: lento, o non parte.": " — {0} GB is borderline: slow, or may not start.",
  "Non c'è abbastanza spazio sul disco.": "Not enough disk space.",
  "Avanti": "Next",
  "Indietro": "Back",
  "Scarica e installa ({0})": "Download and install ({0})",
  "Installazione modelli locali": "Local model installation",
  "Installazione disponibile quando la coda locale e' libera.": "Installation is available when the local queue is idle.",
  "Rimozione modelli locali": "Local model removal",
  "togli i modelli locali": "remove local models",
  "Togliere motori e modelli locali ({0})? Si riscaricano dalla procedura.": "Remove local engines and models ({0})? You can download them again from the wizard.",
  "Le immagini delle vignette (art/, renders/) non si cancellano.": "Panel images (art/, renders/) will not be deleted.",
  "Prova quelli installati": "Test installed models",
  "Prova lo spoglio": "Test breakdown",
  "Prova le immagini": "Test images",
  "Prova {0}": "Test {0}",
  "Prova in coda": "Test queued",
  "Niente di installato da provare.": "No installed models to test.",
  "Il modello delle immagini non è ancora installato.": "The image model is not installed yet.",
  "Il modello per lo spoglio non è ancora installato.": "The breakdown model is not installed yet.",
  "Avvio e provo lo spoglio…": "Starting and testing breakdown…",
  "Avvio e genero un'immagine…": "Starting and generating an image…",
  "Immagine di prova del motore locale": "Local engine test image",
  "«{0}» — {1} s, avvio del motore compreso.": "“{0}” — {1} s, including engine startup.",
  "512×512 in {0} s, avvio del motore compreso. Una vignetta vera, con i riferimenti, chiede di più.": "512×512 in {0} s, including engine startup. A real panel with references takes longer.",
  "Usa i modelli locali": "Use local models",
  "le immagini restano a FLUX.2 [pro] nel cloud": "images still use FLUX.2 [pro] in the cloud",
  "lo spoglio resta a un servizio cloud, o a Ollama": "breakdown still uses a cloud service or Ollama",
  "Ogni motore parte quando serve e si ferma quando parte l'altro: spoglio e immagini vanno a turno, così non si contendono la memoria.": "Each engine starts when needed and stops when the other starts: breakdown and images take turns to avoid competing for memory.",
  ", sul tuo computer con llama.cpp: parte da solo al primo spoglio (la prima volta qualche secondo per caricarlo), e il copione non esce dalla macchina.": ", on your computer with llama.cpp: starts automatically on the first breakdown (initial loading takes a few seconds), and the script stays on your computer.",
  ", sul tuo computer con stable-diffusion.cpp: parte da solo alla prima vignetta, e niente esce dal computer.": ", on your computer with stable-diffusion.cpp: starts automatically on the first panel, and nothing leaves your computer.",
  "; i modelli sono Apache 2.0, e ogni file si verifica col suo checksum.": "; models use Apache 2.0, and each file is verified by checksum.",
  ": per una serie inedita, valuta se è quello che vuoi — lo spoglio locale non lo fa.": ": for an unpublished series, consider whether this is acceptable; local breakdown does not send it away.",
  "Senza immagini (": "Without images (",
  ") il modello ha solo la descrizione, e il personaggio cambia da una vignetta all'altra.": ") the model has only the description, so the character may vary between panels.",
  "Lo stile è dell'opera, non della vignetta:": "Style belongs to the comic, not the panel:",
  "Riferimenti → Stile": "References → Style",
  ": qui sotto, in «servizio e spesa».": ": below, under “service and cost”.",
  "» non ha immagini: con una tavola del luogo la stanza resta la stessa stanza.": "” has no images: a location reference keeps the room consistent.",
  "» non ha una descrizione: il modello riceve solo il nome e reinventa il posto a ogni vignetta.": "” has no description: the model receives only the name and reinvents the place in every panel.",
  "Lavori:": "Jobs:",
  "Locale": "Local",
  "Online testo": "Online text",
  "Online immagini": "Online images",
  "ferma": "stop",
  "Rimuovi il lavoro in attesa": "Remove queued job",
  "Interrompi il lavoro in corso": "Stop running job",
  " · locale": " · local",
  "{0} · locale": "{0} · local",
  "— scritto da te": "— written by you",
  " — scritto da te": " — written by you",
  " — già ritoccato qui": " — already edited here",
  " — parte 1 di {0}": " — part 1 of {0}",
  "Ci sono {0}: {1}{2}.": "There are {0}: {1}{2}.",
  "di": "of",
  "su": "on",
  "In": "In",
  "da generare · ~": "to generate · ~",
  "battuta nuova": "new dialogue",
  "larghezza": "width",
  "Questa vignetta:": "This panel:",
  "Se la esporti tu in": "If you export it to",
  ", si collega da sola.": ", it links automatically.",
  ". Tutto va in": ". Everything goes to",
  "regioni dei pannelli di {0}": "panel regions for {0}",
  "{0} e {1}": "{0} and {1}",
  "{0} di {1}": "{0} of {1}",
  "{0}: immagine {1} di {2}": "{0}: image {1} of {2}",
  "{0} — {1}, {2} pagine": "{0} — {1}, {2} pages",
  "Vignette": "Panels",
  "da dove partire": "starting point",
  "stato": "status",
  "non in locale": "not local",
  "per generare": "to generate",
  "Ruolo": "Role",
  "ruolo": "role",
  "modifica": "edit",
  "Riprendi": "Resume",
  "· se si interrompe, riprendendo si riparte da dove era arrivato.": "· if interrupted, resume continues from where it stopped.",
  "Da cambiare per un proxy o un servizio compatibile: deve esporre": "Change for a proxy or compatible service: it must expose",
  "(la Responses API), non solo": "(the Responses API), not just",
  ". Vuoto, vale quello di OpenAI.": ". Leave empty to use OpenAI's default.",
};