import type { Page } from "@comic-builder/core";

/**
 * Documento di partenza dell'Ispettore: una pagina di esempio, non collegata
 * ai fixture di test del Core (pacchetti separati, contenuti separati).
 */
export const initialPage: Page = {
  schema: 1,
  id: "inspector-demo",
  chapter_id: "inspector-demo-chapter",
  order: 1,
  spread_with: null,
  layout: {
    mode: "page",
    primary_target: "digital-page",
    template_id: "top-splash-3",
    cols: [1, 1, 1],
    rows: [1, 1],
    gutter: { x: 14, y: 18 },
    reading_order: ["demo-01", "demo-02", "demo-03"],
  },
  variants: {},
  overlays: [],
  panels: [
    {
      id: "demo-01",
      scene_id: "demo-scene",
      beat_index: 0,
      source: null,
      area: { col: 0, row: 0, col_span: 3, row_span: 1, z: 0 },
      border: { style: "solid", width: 3, radius: 0 },
      camera: {
        shot: "LS",
        angle: "high",
        lens_mm: 24,
        dof: "deep",
        lighting: "golden",
        mood: "wonder",
        motion: "static",
        subject_placement: "center",
        axis_side: "A-left",
      },
      action: "Il faro sulla scogliera, all'alba",
      setting: "scogliera, mare aperto",
      props: [],
      continuity_notes: "",
      characters: [],
      art: { source: null, status: "missing" },
      prompt: { override: null, negative_override: null },
      control_image: null,
      seed: { mode: "auto", value: null, epoch: 0 },
      render: {},
      balloons: [],
    },
    {
      id: "demo-02",
      scene_id: "demo-scene",
      beat_index: 1,
      source: null,
      area: { col: 0, row: 1, col_span: 2, row_span: 1, z: 0 },
      border: { style: "solid", width: 3, radius: 0 },
      camera: {
        shot: "MS",
        angle: "eye",
        lens_mm: 35,
        dof: "shallow",
        lighting: "soft",
        mood: "calm",
        motion: "static",
        subject_placement: "left-third",
        axis_side: "A-left",
      },
      action: "Sara sale i gradini verso la lanterna",
      setting: "scala a chiocciola del faro",
      props: ["lanterna a olio"],
      continuity_notes: "",
      characters: [
        {
          ref: "sara",
          weight: 0.7,
          role: "lead",
          framing: "full-body",
          expression: "concentrata",
          wardrobe: "default",
        },
      ],
      art: { source: null, status: "missing" },
      prompt: { override: null, negative_override: null },
      control_image: null,
      seed: { mode: "auto", value: null, epoch: 0 },
      render: {},
      balloons: [
        {
          id: "demo-02-b1",
          type: "speech",
          speaker: { ref: "sara", visible: true, offscreen_dir: null },
          text: [{ t: "Ancora pochi gradini." }],
          anchor: { x: 0.08, y: 0.1 },
          tail: { mode: "auto", target: { x: 0.3, y: 0.55 } },
          size_mode: "grow",
          font_scale: 1.0,
          per_target: {},
          z: 2,
          rev: 1,
        },
      ],
    },
    {
      id: "demo-03",
      scene_id: "demo-scene",
      beat_index: 2,
      source: null,
      area: { col: 2, row: 1, col_span: 1, row_span: 1, z: 0 },
      border: { style: "solid", width: 3, radius: 0 },
      camera: {
        shot: "CU",
        angle: "low",
        lens_mm: 85,
        dof: "shallow",
        lighting: "backlit",
        mood: "tense",
        motion: "static",
        subject_placement: "center",
        axis_side: "A-right",
      },
      action: "La luce si accende all'improvviso",
      setting: "cima del faro",
      props: [],
      continuity_notes: "",
      characters: [],
      art: { source: null, status: "missing" },
      prompt: { override: null, negative_override: null },
      control_image: null,
      seed: { mode: "auto", value: null, epoch: 0 },
      render: {},
      balloons: [],
    },
  ],
};
